/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function OptimizedStore (props) {
  const { nodes, materials } = useGLTF('/store-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['NEW WOOD']}
        position={[0.596, 0.774, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials['synthetic_wood.001']}
        position={[2.412, 1.469, 0]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[3.233, 1.043, 1.472]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve003.geometry}
        material={materials['Shiny Metal.001']}
        position={[2.399, 1.587, 0.01]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={1.048}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve011.geometry}
        material={materials['Shiny Metal']}
        position={[2.403, 2.407, 0.037]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.965, 2.181, 1.965]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.front_wall.geometry}
        material={materials.synthetic_wood}
        position={[2.416, 1.517, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[1.529, 13.787, 3.763]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials['RIGHT WALL']}
        position={[-0.757, 1.469, -3.231]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[3.191, 1, 1.47]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials.Rock}
        position={[-0.775, 0, -0.011]}
        scale={[3.191, 3.228, 3.226]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.roof.geometry}
        material={materials['Concrete 1']}
        position={[0, 2.938, 0]}
        scale={[3.946, 13.787, 3.763]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.strips.geometry}
        material={materials['Lamp.001']}
        position={[-0.112, 0.002, -0.027]}
        scale={0.071}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials.LEFT}
        position={[-0.757, 1.469, -3.231]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[3.191, 1, 1.47]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials['BACK WALL']}
        position={[-0.757, 1.469, -3.231]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[3.191, 1, 1.47]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve012.geometry}
        material={materials['Fluorescent Lamp']}
        position={[-0.397, 0.676, -0.453]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.783}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s23Pluse_cream_mat_s23_cream_0.geometry}
        material={materials.mat_s23_cream}
        position={[-0.152, 1.037, 0.446]}
        rotation={[-Math.PI / 2, 0.392, Math.PI / 2]}
        scale={1.064}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s23Pluse_lavender_mat_s23_lavender_0.geometry}
        material={materials.mat_s23_lavender}
        position={[-0.151, 1.037, 0.253]}
        rotation={[-Math.PI / 2, 0.392, Math.PI / 2]}
        scale={1.064}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2001.geometry}
        material={materials['Scene_-_Root']}
        position={[-0.165, 0.925, 0.455]}
        scale={0.001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s23Pluse_cream_mat_s23_cream_0001.geometry}
        material={materials['mat_s23_cream.001']}
        position={[-0.152, 1.037, -0.193]}
        rotation={[-Math.PI / 2, 0.392, Math.PI / 2]}
        scale={1.064}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2003.geometry}
        material={materials['Scene_-_Root.001']}
        position={[-0.165, 0.925, -0.183]}
        scale={0.001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.buttons001.geometry}
        material={nodes.buttons001.material}
        position={[-0.108, 0.894, 1.757]}
        rotation={[Math.PI / 2, 0, 2.387]}
        scale={0.007}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.JEANS_BACK_0003.geometry}
        material={materials['jeans.003']}
        position={[-0.038, 0.487, 1.827]}
        rotation={[3.016, -0.929, 3.068]}
        scale={[0.673, 0.834, 0.67]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lenses001.geometry}
        material={materials['Aviator Glasses.001']}
        position={[-0.107, 1.231, 1.753]}
        rotation={[-3.116, -0.772, -3.107]}
        scale={0.741}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials['bandana white.001']}
        position={[-0.078, 1.148, 1.78]}
        rotation={[-1.577, 0.003, -2.439]}
        scale={0.001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2009.geometry}
        material={materials['shoe.003']}
        position={[-0.052, 0.1, 1.818]}
        rotation={[-Math.PI / 2, 0, -2.462]}
        scale={0.008}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials['bandana black.001']}
        position={[-0.058, 1.147, 1.804]}
        rotation={[-1.577, 0.003, -2.439]}
        scale={0.001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['t-shirt001'].geometry}
        material={materials.PaletteMaterial002}
        position={[-0.055, 0.883, 1.813]}
        rotation={[Math.PI / 2, 0, 2.387]}
        scale={0.007}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mp001.geometry}
        material={materials.Tire}
        position={[-0.039, 0.696, 2.614]}
        rotation={[0, 0, -0.276]}
        scale={0.671}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TireRack_low005.geometry}
        material={materials['Material #0']}
        position={[-0.098, 0.276, 2.613]}
        rotation={[0, -1.571, 0]}
        scale={[0.006, 0.005, 0.002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Base011.geometry}
        material={materials.base}
        position={[1.922, 1.499, 1.444]}
        rotation={[-2.919, 0, -Math.PI]}
        scale={0.239}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vizer_Screw001.geometry}
        material={materials.PaletteMaterial005}
        position={[1.922, 1.495, 1.444]}
        rotation={[-2.919, 0, -Math.PI]}
        scale={0.239}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vizer_Screw005.geometry}
        material={materials.PaletteMaterial006}
        position={[1.922, 1.495, 1.444]}
        rotation={[-2.919, 0, -Math.PI]}
        scale={0.239}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Base003.geometry}
        material={materials.basee}
        position={[1.905, 1.499, 1.903]}
        rotation={[-2.919, 0, -Math.PI]}
        scale={0.241}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cleaner_tin_01.geometry}
        material={materials.cleaner_tin_01}
        position={[1.954, 0.158, 1.341]}
        scale={1.54}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.lubricant_spray_tin.geometry}
        material={materials.lubricant_spray}
        position={[1.946, 0.042, 1.471]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube125.geometry}
        material={materials['Black Plastic.008']}
        position={[1.918, 1.769, -1.582]}
        scale={[0.128, 0.128, 0.472]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane201.geometry}
        material={materials['Material.032']}
        position={[1.803, 1.766, -1.586]}
        rotation={[0, 0, Math.PI / 2]}
        scale={0.723}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BaseballV1.geometry}
        material={materials.BaseballV1Mat}
        position={[1.91, 1.201, -2.015]}
        rotation={[0, 1.571, 0]}
        scale={0.034}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TennisV1.geometry}
        material={materials.TennisV1Mat}
        position={[1.91, 1.201, -1.633]}
        rotation={[0, 1.571, 0]}
        scale={0.032}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TennisV2.geometry}
        material={materials.TennisV2Mat}
        position={[1.91, 1.201, -1.782]}
        rotation={[0, 1.571, 0]}
        scale={0.032}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BasketV1.geometry}
        material={materials.BasketV1Mat}
        position={[1.914, 0.919, -1.842]}
        scale={0.107}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.AFootballV1.geometry}
        material={materials.AFootballV1Mat}
        position={[2.013, 0.882, -2.377]}
        rotation={[0, 1.571, 0]}
        scale={0.127}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BaseballBatV1.geometry}
        material={materials.BaseballBatV1Mat}
        position={[1.921, 1.603, -2.364]}
        rotation={[0.254, -0.007, -0.003]}
        scale={0.312}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BowlingV2.geometry}
        material={materials['BowlingV2Mat.001']}
        position={[1.901, 0.906, -2.799]}
        scale={0.109}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SoccerV1.geometry}
        material={materials.SoccerV1Mat}
        position={[1.913, 1.259, -2.363]}
        scale={0.095}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SoccerV4.geometry}
        material={materials.SoccerV4Mat}
        position={[1.898, 0.471, -1.346]}
        scale={0.096}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.TennisRacketV1.geometry}
        material={materials.TennisRacketV1Mat}
        position={[1.901, 1.697, -2.782]}
        rotation={[0.293, Math.PI / 2, 0]}
        scale={0.307}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.VolleyballV1.geometry}
        material={materials.VolleyballV1Mat}
        position={[1.924, 0.905, -1.354]}
        scale={0.102}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cricket_Glove_Gloves_0.geometry}
        material={materials.Gloves}
        position={[1.909, 1.283, -1.336]}
        rotation={[0, -1.267, 0]}
        scale={0.009}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barres_métal001.geometry}
        material={materials.PaletteMaterial002}
        position={[1.934, 0, -2.545]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.953}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Poignée_métal_noir001.geometry}
        material={materials.PaletteMaterial003}
        position={[1.934, 0, -2.545]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.953}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-__557013001'].geometry}
        material={materials['logoh2r2.002']}
        position={[-0.982, 0.478, -0.01]}
        rotation={[0.006, -0.003, 0]}
        scale={0.779}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-__557022001'].geometry}
        material={materials['filterh2r.002']}
        position={[-0.88, 0.374, 0.338]}
        rotation={[0.006, -0.003, 0]}
        scale={0.779}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-__557202002'].geometry}
        material={materials['exhausth2r.002']}
        position={[-1.022, 0.274, -0.311]}
        rotation={[0.006, -0.003, 0]}
        scale={0.779}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-__557247002'].geometry}
        material={materials['h2brckdisc.002']}
        position={[-0.862, 0.266, -0.527]}
        rotation={[-3.136, 0.003, 0]}
        scale={-0.818}
      />
      <group
        position={[-0.88, 0.266, -0.527]}
        rotation={[0.006, -0.003, 0]}
        scale={0.779}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G-__557256002'].geometry}
          material={materials['treadh2r.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G-__557256002_1'].geometry}
          material={materials['tireh2r.002']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-__557355003'].geometry}
        material={materials['PaletteMaterial001.002']}
        position={[-0.86, 0.233, -0.199]}
        rotation={[0.006, -0.003, 0]}
        scale={0.779}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['G-__557418001'].geometry}
        material={materials['carbonh2r.002']}
        position={[-0.884, 0.662, 0.579]}
        rotation={[0.006, -0.003, 0]}
        scale={0.779}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Base005.geometry}
        material={materials['helmet base.001']}
        position={[0.432, 1.213, 1.469]}
        rotation={[Math.PI, -0.891, Math.PI]}
        scale={0.21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BikerJacket_Leather_0002.geometry}
        material={materials['jacket main.001']}
        position={[0.446, 0.953, 1.472]}
        rotation={[3.139, 0.625, -3.108]}
        scale={[0.009, 0.007, 0.007]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BikerJacket_Metals_0002.geometry}
        material={materials['jacket button.001']}
        position={[0.384, 0.876, 1.379]}
        rotation={[3.139, 0.625, -3.108]}
        scale={[0.009, 0.007, 0.007]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.JEANS_BACK_0002.geometry}
        material={materials['jeans.002']}
        position={[0.444, 0.458, 1.474]}
        rotation={[3.008, -0.997, 3.04]}
        scale={[0.699, 0.829, 0.828]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2011.geometry}
        material={materials['shoe.002']}
        position={[0.413, 0.102, 1.459]}
        rotation={[-Math.PI / 2, 0, -2.343]}
        scale={0.009}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.spoiler001.geometry}
        material={materials['PaletteMaterial003.001']}
        position={[0.432, 1.213, 1.469]}
        rotation={[Math.PI, -0.891, Math.PI]}
        scale={0.21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vizer001.geometry}
        material={materials.PaletteMaterial001}
        position={[0.432, 1.213, 1.469]}
        rotation={[Math.PI, -0.891, Math.PI]}
        scale={0.21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vizer_Screw043.geometry}
        material={materials['PaletteMaterial002.001']}
        position={[0.432, 1.213, 1.469]}
        rotation={[Math.PI, -0.891, Math.PI]}
        scale={0.21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bat_Bat1_0.geometry}
        material={materials['Bat1.001']}
        position={[1.854, 0.079, -1.683]}
        rotation={[Math.PI / 2, 1.358, -Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Hat_CricketEquipments_0001.geometry}
        material={materials['CricketEquipments.004']}
        position={[1.938, 1.444, -1.861]}
        rotation={[0, -0.804, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.head_band001.geometry}
        material={materials['Fine leather black.001']}
        position={[-0.499, 0.776, -2.297]}
        rotation={[-1.884, 0.144, -0.418]}
        scale={1.059}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Headphone_Stand_Aluminum001.geometry}
        material={materials['PaletteMaterial003.002']}
        position={[-0.488, 0.669, -2.365]}
        rotation={[0, -0.018, 0]}
        scale={0.893}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.logo001.geometry}
        material={materials['PaletteMaterial002.002']}
        position={[-0.499, 0.776, -2.297]}
        rotation={[-1.884, 0.144, -0.418]}
        scale={1.059}
      />
      <group
        position={[-0.179, 0.792, -2.558]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.05}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4002.geometry}
          material={materials['monitor.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4002_1.geometry}
          material={materials['Material.008']}
        />
      </group>
      <group
        position={[-0.202, -0.008, -2.578]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.838}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2001_1.geometry}
          material={materials['comp_desk_b.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2001_2.geometry}
          material={materials['comp_desk.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2001_3.geometry}
          material={materials['comp_desk_a.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2001_4.geometry}
          material={materials['comp_desk_c.001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7003.geometry}
        material={materials['material.002']}
        position={[0.273, 0.785, -2.465]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7004.geometry}
        material={materials.PaletteMaterial004}
        position={[0.288, 0.977, -2.496]}
        rotation={[-Math.PI / 2, 0, -0.736]}
        scale={0.002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14001.geometry}
        material={materials['comp_desk_top.001']}
        position={[-0.198, 0.598, -2.484]}
        scale={0.838}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004_red_text__0001.geometry}
        material={materials.PaletteMaterial007}
        position={[-0.741, 0.633, -2.545]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.122}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005_body__0001.geometry}
        material={materials['body.001']}
        position={[-0.741, 0.751, -2.497]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.056}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006_scareen__0001.geometry}
        material={materials['scareen.001']}
        position={[-0.741, 0.751, -2.497]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.056}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane018_button__0001.geometry}
        material={materials['PaletteMaterial001.003']}
        position={[-0.741, 0.751, -2.497]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.056}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_text__0001.geometry}
        material={materials.PaletteMaterial008}
        position={[-0.741, 0.646, -2.631]}
        rotation={[-1.622, 0, 0]}
        scale={0.122}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Group#211002'].geometry}
        material={materials['PaletteMaterial001.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Group#215002'].geometry}
        material={materials['PaletteMaterial001.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Group#250002'].geometry}
        material={materials['PaletteMaterial001.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Group#251002'].geometry}
        material={materials['PaletteMaterial001.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Group#252002'].geometry}
        material={materials['PaletteMaterial001.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Group#281002'].geometry}
        material={materials['PaletteMaterial001.002']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body004.geometry}
        material={materials.plastic_matte_black}
        position={[-1.57, 1.914, -1.446]}
        rotation={[-Math.PI, 0, Math.PI]}
        scale={0.627}
      />
      <group
        position={[-1.57, 1.882, -0.585]}
        rotation={[0, 0, Math.PI]}
        scale={0.627}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lamp_1.geometry}
          material={materials.Plastic_White_Rough}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.lamp_2.geometry}
          material={materials.PaletteMaterial001}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mount002.geometry}
        material={materials.PaletteMaterial003}
        position={[-1.57, 1.957, 0.588]}
        rotation={[-Math.PI, 0, Math.PI]}
        scale={0.627}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WoodenTable_03_body.geometry}
        material={materials.WoodenTable_03}
        position={[-0.121, -0.007, 0.011]}
        rotation={[0, Math.PI / 2, 0]}
        scale={1.077}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2006.geometry}
        material={materials['wire_177028149.003']}
        position={[1.932, 0.797, 1.447]}
        rotation={[-Math.PI / 2, 0, -1.574]}
        scale={0.01}
      />
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube12.geometry}
        material={materials['Material.001']}
        position={[1.893, 0.614, 1.383]}
        rotation={[Math.PI / 2, 0, 1.56]}
        scale={0.039}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials['Rough Iron Steel']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005_1.geometry}
        material={materials.PaletteMaterial002}
      /> */}
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005_2.geometry}
        material={materials.PaletteMaterial002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005_3.geometry}
        material={materials.PaletteMaterial002}
      /> */}
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005_4.geometry}
        material={materials['Leather.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005_5.geometry}
        material={materials.PaletteMaterial004}
      /> */}
    </group>
  )
}

useGLTF.preload('/store-transformed.glb')
