/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\models\Flannel shirt\scene.gltf -o .\src\models\Shirt.jsx -k -T
Author: CG StudioX (https://sketchfab.com/CG_StudioX)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/red-flannel-shirt-b7c5c6572c864c3ab3a2e7696e3521eb
Title: Red Flannel Shirt
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/models/Flannel shirt/scene-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				name="polySurface2_lambert2_0"
				geometry={nodes.polySurface2_lambert2_0.geometry}
				material={materials.lambert2}
				scale={0.01}
			/>
		</group>
	);
}

useGLTF.preload("/models/Flannel shirt/scene-transformed.glb");
