/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\models\sunglass\scene.gltf -o .\src\models\Sunglass.jsx -k -T
Author: FrancescoMilanese (https://sketchfab.com/FrancescoMilanese)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/sunglasses-aviator-33aa237d3814419abf979b1432213ad1
Title: Sunglasses aviator
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/models/sunglass/scene-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh name="defaultMaterial" geometry={nodes.defaultMaterial.geometry} material={materials.sunglasses_aviator} />
		</group>
	);
}

useGLTF.preload("/models/sunglass/scene-transformed.glb");
