/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\models\Tigerman\scene.gltf -o .\src\models\Tigerman.jsx -k -T
Author: SKYE (https://sketchfab.com/FreeGator)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/tiger-01d685032bb7401a90a57d2c775d7cd9
Title: Tiger
*/

import React, { useRef, forwardRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const Model = forwardRef((props, ref) => {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/models/Tigerman/scene-transformed.glb");
	const { actions } = useAnimations(animations, group);
	return (
		<group ref={ref} {...props} dispose={null} name="Tigerman.jsx">
			<group name="Sketchfab_Scene">
				<primitive object={nodes._rootJoint} />
				<skinnedMesh
					name="Object_10"
					geometry={nodes.Object_10.geometry}
					material={materials.Eyes}
					skeleton={nodes.Object_10.skeleton}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.018}
				/>
				<skinnedMesh
					name="Object_11"
					geometry={nodes.Object_11.geometry}
					material={materials.Shine}
					skeleton={nodes.Object_11.skeleton}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.018}
				/>
				<skinnedMesh
					name="Object_13"
					geometry={nodes.Object_13.geometry}
					material={materials.PantherNaked_Final}
					skeleton={nodes.Object_13.skeleton}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.018}
				/>
				<skinnedMesh
					name="Object_14"
					geometry={nodes.Object_14.geometry}
					material={materials.Mouth_Cat}
					skeleton={nodes.Object_14.skeleton}
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.018}
				/>
			</group>
		</group>
	);
});

useGLTF.preload("/models/Tigerman/scene-transformed.glb");

export default Model;
