/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 ./public/models/Arab Man/scene.gltf -o .\src\models\Arab.jsx -k -T
Author: Marc Sawyer (https://sketchfab.com/whitewashstudio)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/arab-man-3d-people-archviz-b61c9fabedd3414c823c916c268db8f6
Title: Arab Man 3d People - Archviz
*/

import React, { forwardRef, useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Model = forwardRef((props, ref) => {
	const { nodes, materials } = useGLTF("/models/Arab Man/scene-transformed.glb");
	return (
		<group ref={ref} {...props} dispose={null} name="Arab.jsx">
			<mesh
				name="ArabMan244_Headdress_0"
				geometry={nodes.ArabMan244_Headdress_0.geometry}
				material={materials.Headdress}
				scale={0.01}
			/>
			<mesh
				name="ArabMan244_Robe_0"
				geometry={nodes.ArabMan244_Robe_0.geometry}
				material={materials.Robe}
				scale={0.01}
			/>
			<mesh
				name="ArabMan244_RobeCollar_0"
				geometry={nodes.ArabMan244_RobeCollar_0.geometry}
				material={materials.PaletteMaterial001}
				scale={0.01}
			/>
			<mesh
				name="ArabMan244_Sandals_0"
				geometry={nodes.ArabMan244_Sandals_0.geometry}
				material={materials.Sandals}
				scale={0.01}
			/>
			<mesh
				name="ArabMan244_Cornia_L_0"
				geometry={nodes.ArabMan244_Cornia_L_0.geometry}
				material={materials.Cornia_L}
				scale={0.01}
			/>
			<mesh
				name="ArabMan244_Nails_0"
				geometry={nodes.ArabMan244_Nails_0.geometry}
				material={materials.Nails}
				scale={0.01}
			/>
			<mesh
				name="ArabMan244_Material11973_0"
				geometry={nodes.ArabMan244_Material11973_0.geometry}
				material={materials.Material11973}
				scale={0.01}
			/>
			<mesh
				name="ArabMan244_Material11985_0"
				geometry={nodes.ArabMan244_Material11985_0.geometry}
				material={materials.Material11985}
				scale={0.01}
			/>
			<mesh
				name="ArabMan244_Arm_0"
				geometry={nodes.ArabMan244_Arm_0.geometry}
				material={materials.material}
				scale={0.01}
			/>
			<mesh
				name="ArabMan244_eye_occ_R_0"
				geometry={nodes.ArabMan244_eye_occ_R_0.geometry}
				material={materials.PaletteMaterial002}
				scale={0.01}
			/>
			<mesh
				name="ArabMan244_Head_0"
				geometry={nodes.ArabMan244_Head_0.geometry}
				material={materials.Head}
				scale={0.01}
			/>
			<mesh
				name="ArabMan244_Material12003_0"
				geometry={nodes.ArabMan244_Material12003_0.geometry}
				material={materials.Material12003}
				scale={0.01}
			/>
			<mesh
				name="ArabMan244_Leg_0"
				geometry={nodes.ArabMan244_Leg_0.geometry}
				material={materials.material_17}
				scale={0.01}
			/>
			<mesh
				name="ArabMan244_Eyelash_0"
				geometry={nodes.ArabMan244_Eyelash_0.geometry}
				material={materials.Eyelash}
				scale={0.01}
			/>
		</group>
	);
});

useGLTF.preload("/models/Arab Man/scene-transformed.glb");

export default Model;
