/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\models\Backpack\scene.gltf -o .\src\models\Backpack.jsx -k -T
Author: Karolina Renkiewicz (https://sketchfab.com/KarolinaRenkiewicz)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/leather-backpack-low-poly-8609be0defe645bc95878d3cfb15b536
Title: Leather Backpack - low poly
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/models/Backpack/scene-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				name="Backpack_lp_Backpack_0"
				geometry={nodes.Backpack_lp_Backpack_0.geometry}
				material={materials.Backpack}
				position={[-0.001, -0.064, 0.08]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.001}
			/>
		</group>
	);
}

useGLTF.preload("/models/Backpack/scene-transformed.glb");
