/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\models\Bandana\scene.gltf -o .\src\models\Bandana.jsx -k -T
Author: Pieter Ferreira (https://sketchfab.com/Badboy17Aiden)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/skull-bandana-c5ce35f1620c421f9510824ea42f7bc7
Title: Skull Bandana
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/models/Bandana/scene-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				name="Object_2"
				geometry={nodes.Object_2.geometry}
				material={materials.PT_FABRIC_FRONT_21982}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.012}
			/>
			<mesh
				name="Object_3"
				geometry={nodes.Object_3.geometry}
				material={materials.Material23442}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.012}
			/>
			<mesh
				name="Object_7"
				geometry={nodes.Object_7.geometry}
				material={materials.Material3765_FRONT_3764}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={0.012}
			/>
		</group>
	);
}

useGLTF.preload("/models/Bandana/scene-transformed.glb");
