/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\models\Boots and gloves 1\scene.gltf -o .\src\models\BootsAndGloves.jsx -k -T
Author: CreysArt (https://sketchfab.com/CreysArt)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/boots-and-gloves-low-poly-game-ready-2ce8de7dc2424858807aa57f180ff4a4
Title: Boots and gloves, low poly game ready
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/models/Boots and gloves 1/scene-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				name="Object_2"
				geometry={nodes.Object_2.geometry}
				material={materials.wire_177028149}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
		</group>
	);
}

useGLTF.preload("/models/Boots and gloves 1/scene-transformed.glb");
