/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\models\Boots\scene.gltf -o .\src\models\Boots.jsx -k -T
Author: thegreen3d (https://sketchfab.com/thegreen3d)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/boots-8cae8dfefe3e48c782cf1fe678e7052c
Title: Boots
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/models/Boots/scene-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				name="Mesh_Render_Clay_0"
				geometry={nodes.Mesh_Render_Clay_0.geometry}
				material={materials.Render_Clay}
				scale={0.01}
			/>
		</group>
	);
}

useGLTF.preload("/models/Boots/scene-transformed.glb");
