/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\models\helmet\scene.gltf -o .\src\models\Helmet.jsx -k -T
Author: melvinx (https://sketchfab.com/melvinx)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/vintage-agv-helmet-0333827ff0a44cfcbee50fdf868f3625
Title: vintage agv helmet
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/models/helmet/scene-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				name="defaultMaterial"
				geometry={nodes.defaultMaterial.geometry}
				material={materials.prop_helmet_agv_glass_leather}
				scale={0.141}
			/>
			<mesh
				name="defaultMaterial_1"
				geometry={nodes.defaultMaterial_1.geometry}
				material={materials.prop_helmet_agv_strap_leather}
				scale={0.141}
			/>
			<mesh
				name="defaultMaterial_2"
				geometry={nodes.defaultMaterial_2.geometry}
				material={materials.prop_helmet_agv_chrome}
				scale={0.141}
			/>
			<mesh
				name="defaultMaterial_3"
				geometry={nodes.defaultMaterial_3.geometry}
				material={materials.prop_helmet_agv_glass}
				scale={0.141}
			/>
			<mesh
				name="defaultMaterial_4"
				geometry={nodes.defaultMaterial_4.geometry}
				material={materials.prop_helmet_agv_strap}
				scale={0.141}
			/>
			<mesh
				name="defaultMaterial_5"
				geometry={nodes.defaultMaterial_5.geometry}
				material={materials.prop_helmet_agv_stitch}
				scale={0.141}
			/>
			<mesh
				name="defaultMaterial_6"
				geometry={nodes.defaultMaterial_6.geometry}
				material={materials.prop_helmet_agv_white}
				scale={0.141}
			/>
			<mesh
				name="defaultMaterial_7"
				geometry={nodes.defaultMaterial_7.geometry}
				material={materials.prop_helmet_agv_leather}
				scale={0.141}
			/>
			<mesh
				name="defaultMaterial_8"
				geometry={nodes.defaultMaterial_8.geometry}
				material={materials.prop_helmet_agv_inside}
				scale={0.141}
			/>
			<mesh
				name="defaultMaterial_9"
				geometry={nodes.defaultMaterial_9.geometry}
				material={materials.prop_helmet_agv_grey}
				scale={0.141}
			/>
		</group>
	);
}

useGLTF.preload("/models/helmet/scene-transformed.glb");
