/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\models\Jacket 1\scene.gltf -o .\src\models\Jacket.jsx -k -T
Author: 3dia (https://sketchfab.com/3dia)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/male-biker-jacket-d09326aff3514343b723302c01965598
Title: Male Biker Jacket
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/models/Jacket 1/scene-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				name="BikerJacket_Leather_0"
				geometry={nodes.BikerJacket_Leather_0.geometry}
				material={materials.Leather}
				scale={0.012}
			/>
			<mesh
				name="BikerJacket_Metals_0"
				geometry={nodes.BikerJacket_Metals_0.geometry}
				material={materials.Metals}
				scale={0.012}
			/>
		</group>
	);
}

useGLTF.preload("/models/Jacket 1/scene-transformed.glb");
