/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\models\Jeans\scene.gltf -o .\src\models\Jeans.jsx -k -T
Author: Marc Sawyer (https://sketchfab.com/whitewashstudio)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-rise-skinny-jeans-0152b1372e3e43e58a339226e64306ba
Title: Low Rise Skinny Jeans
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/models/Jeans/scene-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh name="JEANS_BACK_0" geometry={nodes.JEANS_BACK_0.geometry} material={materials.BACK} scale={100} />
			<mesh name="JEANS_FRONT_0" geometry={nodes.JEANS_FRONT_0.geometry} material={materials.FRONT} scale={100} />
		</group>
	);
}

useGLTF.preload("/models/Jeans/scene-transformed.glb");
