/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\models\Man in Jeans\scene.gltf -o .\src\models\ManInJeans.jsx -k -T
Author: 3DFarm (https://sketchfab.com/3dfarm)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/man-in-jeans-1053-42e361cc93c3452d90062bf0803b6a99
Title: Man in jeans 1053
*/

import React, { forwardRef, useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Model = forwardRef((props, ref) => {
	const { nodes, materials } = useGLTF("/models/Man in Jeans/scene-transformed.glb");
	return (
		<group ref={ref} {...props} dispose={null} name="ManInJeans.jsx">
			<mesh
				name="Object_2"
				geometry={nodes.Object_2.geometry}
				material={materials.defaultMat}
				position={[-331.199, 4.403, 263.333]}
				rotation={[-0.198, -1.518, 2.972]}
			/>
		</group>
	);
});

useGLTF.preload("/models/Man in Jeans/scene-transformed.glb");

export default Model;
