/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\models\Man in suit\scene.gltf -o .\src\models\ManInSuit.jsx -k -T
Author: 3DFarm (https://sketchfab.com/3dfarm)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/man-in-a-business-suit-0297-fac5544d559e41ba9a9bfb5536041de3
Title: Man in a business suit 0297
*/

import React, { forwardRef, useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Model = forwardRef((props, ref) => {
	const { nodes, materials } = useGLTF("/models/Man in suit/scene-transformed.glb");
	return (
		<group ref={ref} {...props} dispose={null} name="ManInSuit.jsx">
			<mesh
				name="Object_2"
				geometry={nodes.Object_2.geometry}
				material={materials.defaultMat}
				position={[-314.93, -92.733, 357.245]}
				rotation={[3.074, -0.033, -0.009]}
			/>
		</group>
	);
});

useGLTF.preload("/models/Man in suit/scene-transformed.glb");

export default Model;
