/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\models\Man with polo shirt\scene.gltf -o .\src\models\ManWithShirt.jsx -k -T
Author: manoeldarochadeoliveira (https://sketchfab.com/manoeldarochadeoliveira)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/casual-man-with-polo-shirt-with-vrchat-visemes-9da5478ada084d24a3d7cb04596d3bd2
Title: Casual Man with Polo Shirt - With VRCHAT VISEMES
*/

import React, { useRef, forwardRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const Model = forwardRef((props, ref) => {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/models/Man with polo shirt/scene-transformed.glb");
	const { actions } = useAnimations(animations, group);
	return (
		<group ref={ref} {...props} dispose={null} name="ManWithShirt.jsx">
			<group name="Sketchfab_Scene">
				<group name="Object_5" rotation={[-Math.PI / 2, 0, 0]} scale={1.111}>
					<skinnedMesh
						name="Object_83"
						geometry={nodes.Object_83.geometry}
						material={materials.Material}
						skeleton={nodes.Object_83.skeleton}
						morphTargetDictionary={nodes.Object_83.morphTargetDictionary}
						morphTargetInfluences={nodes.Object_83.morphTargetInfluences}
					/>
				</group>
				<primitive object={nodes._rootJoint} />
			</group>
		</group>
	);
});

useGLTF.preload("/models/Man with polo shirt/scene-transformed.glb");

export default Model;
