/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\models\Yamaha R1\scene.gltf -o .\src\models\Yamaha.jsx -k -T
Author: Sim3D (https://sketchfab.com/simed)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/yamaha-yzf-r1-ready-to-print-stl-file-22c0aef53c7e4e7a931ce22693909a70
Title: Yamaha YZF R1  Ready to Print STL File
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/models/Yamaha R1/scene-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				name="Object_2"
				geometry={nodes.Object_2.geometry}
				material={materials["Scene_-_Root"]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
		</group>
	);
}

useGLTF.preload("/models/Yamaha R1/scene-transformed.glb");
